title: Code Cats Blog
logo: /assets/img/logo.png
description: Welcome to the blog site. The purpose of the blog is to share ideas with other coders and consistently improve my work.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
